### ISSUE TITLE
Solar System and Galaxy out of bounds

### ISSUE THREAD

**Issue by LargoUsagi** [retro-game/retro-game#1]
You can go to solar systems > 500 and galaxies > 5 by manually typing in the number and hitting enter.

It produces a URL like http://somegamesite.com/galaxy?body=3&galaxy=1337&system=1

This probably could use a bounds check.  Unfortunately I am traveling or I would figure out how to do this and make a pull but I figured I would let you know.

**Comment by bartekmaciejowski** [comment]
YES PLEASE FIX

**Comment by patrykstefanski** [comment]
Fixed
