### ISSUE TITLE
Allow switching of planets/moons in empire view

### ISSUE THREAD

**Issue by sbraun90** [retro-game/retro-game#29]
Clicking in the empire view on a body picture or body coordinates switches the current body to this body.

Currently, clicking on the coordinates goes to the galaxy view. It has to be decided if this behaviour should be changed.

**Comment by patrykstefanski** [comment]
I believe that clicking on the coordinates to go to the galaxy view and clicking on a body picture to switch to the corresponding body is fine. Clicking on a picture was added in the referenced commit. If anyone disagrees, please reopen this issue.
