### ISSUE TITLE
Force String.format to use the US-Locale

### ISSUE THREAD

**Issue by sbraun90** [retro-game/retro-game#30]
If the system locale is german the update of statistics fails, because the numbers are wrongly formatted and PSQL cannot correctly interpret them.
Quickfix:  import java.util.Locale; String.format(Locale.US, ...);

Open question: Is there a more central place to set the locale, so that we do not have to add it to every String.format statement?

**Comment by gaius1304** [comment]
Should be fixed in 590f900d47567e948ba9540d708b7b4ad6d6b13e.
