### ISSUE TITLE
Resources calculated incorrectly when the capacity is reached

### ISSUE THREAD

**Issue by patrykstefanski** [retro-game/retro-game#32]
Assume that:
- there is 0 deuterium on a planet
- the deuterium synthesizer produces 3 deuterium per second
- the deuterium capacity is 100

Then, after 33 seconds there will be 99 deuterium on that planet. However, after another 1 second, there still will be 99 deuterium (it should be 100).

The reason for that is the resource calculation that considers only the seconds when a resource can be produced at full speed. The last second should be taken into account as a special case.

Metal and crystal are calculated incorrectly as well, but since by default they are produced as a base income, the bug can be easily overlooked.

**Comment by Mijago** [comment]
Addition: It was never intended that the base production overflows the storage capacity! Should be fixed in the same PR.
https://owiki.de/index.php?title=Grundproduktion

**Comment by gaius1304** [comment]
Should be fixed in b469b5892e360158b5c0149dd00dfb103ddaae6d.
