### ISSUE TITLE
Sending attack fleet on noob protection target shows /error page

### ISSUE THREAD

**Issue by lsrom** [retro-game/retro-game#41]
Bug: Attacking player under noob protection shows /error page without any explanation and log shows WrongTargetUserException with generic message.

Fix? Should be better presented to the user (I assume you just haven't got around to it) and ingame logs should also better reflect what actually failed. Currently all checks have the same message and exception (FlightServiceImpl).

**Comment by gaius1304** [comment]
Should be fixed in 02a1665ef55c3a4b523bd7cbbe97041005b62c19.
